kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mnmo-operator
subjects:
- kind: ServiceAccount
  name: mnmo-operator
  # Replace this with the namespace the operator is deployed in.
  namespace: openshift-machine-api
roleRef:
  kind: ClusterRole
  name: mnmo-operator
  apiGroup: rbac.authorization.k8s.io
