apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mnmo-rb
  namespace: openshift-machine-api
subjects:
- kind: ServiceAccount
  name: mnmo-operator
  namespace: openshift-machine-api
roleRef:
  kind: Role 
  name: mnmo-operator 
  apiGroup: rbac.authorization.k8s.io
